import type { Duration, Mood, Pace, Vibe } from "./types";

export const hy = {
  brand: "ԿինոՄան",
  tagline: "Գտի՛ր կատարյալ ֆիլմը կամ սերիալը",
  heroLead:
    "Հարցաշար, տրամադրություն և խելացի առաջարկներ՝ մեկ կինեմատիկ երեկոյի համար։",
  nav: {
    home: "Գլխավոր",
    quiz: "Հարցաշար",
    search: "Որոնում",
    wishlist: "Իմ ցանկը",
  },
  cta: {
    quiz: "Հարցաշար",
    pair: "Couch Match",
    surprise: "Անակնկալ",
    search: "Որոնել ֆիլմ",
    start: "Սկսել",
    next: "Հաջորդ",
    back: "Հետ",
    results: "Տեսնել առաջարկները",
    trailer: "Թրեյլեր",
    addWishlist: "Ավելացնել ցանկում",
    removeWishlist: "Հանել ցանկից",
    close: "Փակել",
    retry: "Կրկին փորձել",
  },
  home: {
    quizTitle: "Ինտերակտիվ հարցաշար",
    quizText: "Չորս քայլ՝ տրամադրություն, վայբ, տեմպ և տևողություն։",
    pairTitle: "Couch Match",
    pairText: "Երկու հոգի պատասխանում են, մենք գտնում ենք ընդհանուր ֆիլմը։",
    surpriseTitle: "Անակնկալ",
    surpriseText: "Թաքնված գոհարներ՝ երբ չգիտես՝ ինչ ես ուզում։",
  },
  quiz: {
    soloTitle: "Ի՞նչ ես ուզում դիտել այսօր",
    pairTitle: "Couch Match",
    player: (n: number) => `Օգտատեր ${n}`,
    playerHint: "Յուրաքանչյուրը պատասխանում է նույն չորս հարցերին։",
    steps: {
      mood: "Տրամադրություն",
      vibe: "Վիզուալ վայբ",
      pace: "Տեմպ",
      duration: "Տևողություն",
    },
    loading: "Ընտրում ենք քո երեկոն…",
    empty: "Առաջարկ չգտնվեց։ Փորձիր այլ պատասխաններ։",
    error: "Չհաջողվեց բեռնել առաջարկները։",
  },
  moods: {
    happy: { label: "Ուրախ", hint: "Ծիծաղ, ջերմություն, թեթև երեկո" },
    sad: { label: "Տխուր", hint: "Խոր դրամա և զգացմունք" },
    tense: { label: "Լարված", hint: "Թրիլեր, սուսպենս, ադրենալին" },
    romantic: { label: "Ռոմանտիկ", hint: "Սեր և մեղմ լույս" },
    adventurous: { label: "Արկածային", hint: "Ճանապարհ, էպիկ և գործողություն" },
    chill: { label: "Հանգիստ", hint: "Առանց շտապելու, փափուկ ռիթմ" },
  } satisfies Record<Mood, { label: string; hint: string }>,
  vibes: {
    colorful: { label: "Գունեղ", hint: "Պայծառ կադրեր և ֆանտազիա" },
    dark: { label: "Մութ", hint: "Նուար, ստվերներ, լարվածություն" },
    vintage: { label: "Ռետրո", hint: "Դարաշրջանի հմայք և պատմություն" },
    neon: { label: "Նեոն", hint: "Գիշերային քաղաք և ֆուտուրիզմ" },
    natural: { label: "Բնական", hint: "Բնություն, օդ, իրականություն" },
  } satisfies Record<Vibe, { label: string; hint: string }>,
  paces: {
    slow: { label: "Դանդաղ", hint: "Խոսակցություններ և մթնոլորտ" },
    medium: { label: "Միջին", hint: "Հավասարակշռված պատմություն" },
    fast: { label: "Արագ", hint: "Դինամիկ կտրվածք և էներգիա" },
  } satisfies Record<Pace, { label: string; hint: string }>,
  durations: {
    short: { label: "Կարճ", hint: "Մինչև ~100 րոպե" },
    feature: { label: "Ֆիլմ", hint: "Դասական տևողություն" },
    epic: { label: "Էպոս", hint: "Երկար, մեծ կտավ" },
    series: { label: "Սերիալ", hint: "Բազմասերիա երեկո" },
  } satisfies Record<Duration, { label: string; hint: string }>,
  card: {
    reason: "Ինչու հենց սա",
    snack: "Խորտիկ",
    year: "Տարի",
    rating: "Գնահատական",
    series: "Սերիալ",
    movie: "Ֆիլմ",
  },
  search: {
    title: "Որոնում",
    placeholder: "Ֆիլմի կամ սերիալի անուն…",
    genre: "Ժանր",
    rating: "Գնահատական",
    year: "Տարի",
    all: "Բոլորը",
    empty: "Ոչինչ չգտնվեց։ Փոխիր ֆիլտրերը կամ հարցումը։",
    hint: "Գրիր վերնագիր կամ օգտագործիր ֆիլտրերը։",
  },
  wishlist: {
    title: "Իմ ցանկը",
    empty: "Ցանկը դեռ դատարկ է։ Ավելացրու ֆիլմեր սրտիկով։",
  },
  trailer: {
    missing: "Թրեյլեր չկա",
    loading: "Բեռնում ենք թրեյլերը…",
  },
  footer: "ԿինոՄան · կինեմատիկ երեկոներ հայերեն",
};

export const genreHy: Record<number, string> = {
  28: "Մարտաֆիլմ",
  12: "Արկածային",
  16: "Անիմացիա",
  35: "Կատակերգություն",
  80: "Քրեական",
  99: "Վավերագրական",
  18: "Դրամա",
  10751: "Ընտանեկան",
  14: "Ֆանտազիա",
  36: "Պատմական",
  27: "Սարսափ",
  10402: "Երաժշտական",
  9648: "Առեղծված",
  10749: "Մելոդրամա",
  878: "Գիտաֆանտաստիկա",
  10770: "Հեռուստաֆիլմ",
  53: "Թրիլեր",
  10752: "Պատերազմ",
  37: "Վեսթերն",
  10759: "Մարտ և արկած",
  10762: "Մանկական",
  10765: "Ֆանտաստիկա",
  10768: "Պատերազմ և քաղաքականություն",
};

export const genreFilterOptions = [
  { id: 28, label: genreHy[28] },
  { id: 12, label: genreHy[12] },
  { id: 16, label: genreHy[16] },
  { id: 35, label: genreHy[35] },
  { id: 18, label: genreHy[18] },
  { id: 27, label: genreHy[27] },
  { id: 10749, label: genreHy[10749] },
  { id: 878, label: genreHy[878] },
  { id: 53, label: genreHy[53] },
  { id: 99, label: genreHy[99] },
  { id: 10751, label: genreHy[10751] },
];
